---
- hosts: localhost
  tasks:
  - name: cleanup old install
    shell: rm -rf /var/tmp/ocp4-deployconfigs/

  - name: install packages required for the installer setup
    become: true
    yum:
      state: present
      name:
      - python-netaddr
      - httpd

  - name: fetch installer
    get_url:
      url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ ocp_clients_version }}/openshift-install-linux-{{ ocp_clients_version }}.tar.gz
      dest: /var/tmp/openshift-install-linux-{{ ocp_clients_version }}.tar.gz
      checksum: md5:d29ba3712b5b268e16adca8ad09dffa3

  - name: fetch clients
    get_url:
      url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ ocp_clients_version }}/openshift-client-linux-{{ ocp_clients_version }}.tar.gz
      dest: /var/tmp/openshift-client-linux-{{ ocp_clients_version }}.tar.gz
      checksum: md5:ceb34d82ed9932a079addf68ce2520d6

  - name: extract installer
    become: true
    unarchive:
      src: /var/tmp/openshift-install-linux-{{ ocp_clients_version }}.tar.gz
      dest: /usr/local/bin
      mode: +x

  - name: extract clients
    become: true
    unarchive:
      src: /var/tmp/openshift-client-linux-{{ ocp_clients_version }}.tar.gz
      dest: /usr/local/bin
      mode: +x

  - name: create installation directory
    file:
      path: /var/tmp/ocp4-deployconfigs
      state: directory
      mode: 0755
  #    owner: openshift-installer
  #    group: openshift-installer

  - name: copy config file to correct place
    template:
      src: templates/install-config.yaml.j2
      dest: /var/tmp/ocp4-deployconfigs/install-config.yaml
      mode: 0755

  - name: take a copy of install-config.yaml file to home directory
    template:
      src: templates/install-config.yaml.j2
      dest: /var/tmp/install-config.yaml
      mode: 0755

  - name: create ignition configs
    shell: "/usr/local/bin/openshift-install create ignition-configs --dir=/var/tmp/ocp4-deployconfigs"

  - name: copy bootstrap ignition file to public dir
    become: true
    copy:
      src: /var/tmp/ocp4-deployconfigs/bootstrap.ign
      dest: /var/www/html/bootstrap.ign
      remote_src: yes

  - name: copy master ignition file to public dir
    become: true
    copy:
      src: /var/tmp/ocp4-deployconfigs/master.ign
      dest: "/var/www/html/{{ hostvars[item]['inventory_hostname_short'] }}.ign"
      remote_src: yes
    with_items:
        - "{{ groups['masters'] | sort }}"

  - name: copy worker ignition file to public dir
    become: true
    copy:
      src: /var/tmp/ocp4-deployconfigs/worker.ign
      dest: "/var/www/html/{{ hostvars[item]['inventory_hostname_short'] }}.ign"
      remote_src: yes
    with_items:
        - "{{ groups['workers'] | sort }}"
