- hosts: masters
  become: yes
  tasks:
  - name: Set static ips for masters
    shell: "nmcli con mod 'Wired connection 1'  ipv4.method manual ipv4.gateway {{ masters_gw }} ipv4.addresses {{ ip }}/{{ (ip + '/' + masters_nm) | ipaddr('prefix') }}"
  - name: add search domains
    shell: "nmcli con mod 'Wired connection 1' +ipv4.dns-search {{item}}"
    with_items:
      - '{{domain}}'
      - "{{base_domain}}"
  - name: add dns 
    shell: "nmcli con mod 'Wired connection 1' +ipv4.dns {{item}}"
    with_items:
      - '{{dns}}'
  - name: set hostname
    shell: "hostnamectl set-hostname {{fqdn}}"

- hosts: workers
  become: yes
  tasks:
  - name: Set static ips for workers
    shell: "nmcli con mod 'Wired connection 1'  ipv4.method manual ipv4.gateway {{ workers_gw }} ipv4.addresses {{ ip }}/{{ (ip + '/' + workers_nm) | ipaddr('prefix') }}"
  - name: add search domains
    shell: "nmcli con mod 'Wired connection 1' +ipv4.dns-search {{item}}"
    with_items:
      - '{{domain}}'
      - "{{base_domain}}"
  - name: add dns 
    shell: "nmcli con mod 'Wired connection 1' +ipv4.dns {{item}}"
    with_items:
      - '{{dns}}'
  - name: set hostname
    shell: "hostnamectl set-hostname {{fqdn}}"

- hosts: infra
  become: yes
  tasks:
  - name: Set static ips for infra
    shell: "nmcli con mod 'Wired connection 1'  ipv4.method manual ipv4.gateway {{ infra_gw }} ipv4.addresses {{ ip }}/{{ (ip + '/' + infra_nm) | ipaddr('prefix') }}"
  - name: add search domains
    shell: "nmcli con mod 'Wired connection 1' +ipv4.dns-search {{item}}"
    with_items:
      - '{{domain}}'
      - "{{base_domain}}"
  - name: add dns 
    shell: "nmcli con mod 'Wired connection 1' +ipv4.dns {{item}}"
    with_items:
      - '{{dns}}'
  - name: set hostname
    shell: "hostnamectl set-hostname {{fqdn}}"